#!/usr/bin/env node
// build-sw.mjs — regenerates sw.js, the flove service worker.
//
// Full-offline PWA: the worker precaches the whole runnable site so every app
// works with no network once installed. Source of truth = the tracked files
// (`git ls-files`), same principle as build-flove-zip.sh, so the precache list
// always matches what flove.org serves. Run this before publishing (or from
// build-flove-zip.sh) whenever site files change, then commit sw.js.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const ROOT = new URL('.', import.meta.url).pathname;

// Runtime asset types worth caching for offline. (No .sh/.mjs/.md/dev config.)
const ALLOW = new Set([
  'html', 'css', 'js', 'json', 'svg', 'png', 'jpg', 'jpeg', 'gif', 'webp',
  'ico', 'webmanifest', 'woff', 'woff2', 'ttf', 'otf', 'mp3', 'mp4', 'webm',
]);

// Never precache these (build outputs, dev config, machine data, huge non-runtime).
const DENY_EXACT = new Set([
  'sw.js', 'build-sw.mjs', 'build-flove-zip.sh', 'build-aliases.mjs',
  'publish-lowai.sh', 'flove.zip', 'cloudinary-urls.json',
  '.cloudinary-progress.json', '.htmlvalidate.json',
]);
// Web-only extras kept live but out of the offline app (mirrors the zip).
const DENY_DIRS = ['blog/', 'apps/lowai/', 'apps/ephemerall/', 'docs/superpowers/'];
const DENY_PREFIX_FILES = ['apps/anim-form.html'];

const tracked = execSync('git ls-files', { cwd: ROOT, encoding: 'utf8' })
  .split('\n').map(s => s.trim()).filter(Boolean);

const files = tracked.filter(p => {
  const ext = p.split('.').pop().toLowerCase();
  if (!ALLOW.has(ext)) return false;
  if (DENY_EXACT.has(p)) return false;
  if (DENY_DIRS.some(d => p.startsWith(d))) return false;
  if (DENY_PREFIX_FILES.includes(p)) return false;
  return true;
});

// Version hash from file contents → bumps whenever any cached file changes,
// which triggers the worker's activate cleanup + re-cache on next publish.
// Bump SW_REV when the worker's *logic* changes (not just cached files), so
// existing installs get a new cache name and drop the stale one on activate.
const SW_REV = 2;
const hash = createHash('sha256');
hash.update('rev' + SW_REV);
for (const p of files.sort()) hash.update(p).update(readFileSync(`${ROOT}${p}`));
const VERSION = 'flove-' + hash.digest('hex').slice(0, 10);

// Root-absolute URLs; '/' aliases index.html for a bare flove.org visit.
const urls = ['/', ...files.map(p => '/' + p)];

const sw = `// sw.js — GENERATED by build-sw.mjs. Do not edit by hand.
// flove service worker: full-offline precache (${urls.length} entries).
const VERSION = ${JSON.stringify(VERSION)};
const PRECACHE = ${JSON.stringify(urls, null, 0)};

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(VERSION);
    // Cache each entry independently so one odd file can't abort the whole install.
    await Promise.allSettled(PRECACHE.map((u) => cache.add(u)));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== location.origin) return;

  const isPage = req.mode === 'navigate' ||
    (req.headers.get('accept') || '').includes('text/html');

  if (isPage) {
    // Pages: NETWORK-FIRST so an online visit always shows the latest content;
    // fall back to cache (then the gate) only when offline. Prevents the
    // "I published but still see the old page" service-worker trap.
    e.respondWith((async () => {
      try {
        const res = await fetch(req);
        if (res && res.ok && res.type === 'basic') {
          const cache = await caches.open(VERSION);
          cache.put(req, res.clone());
        }
        return res;
      } catch (err) {
        const cached = await caches.match(req, { ignoreSearch: true });
        if (cached) return cached;
        const gate = await caches.match('/launch.html');
        if (gate) return gate;
        throw err;
      }
    })());
    return;
  }

  // Assets (css/js/img/…): CACHE-FIRST for speed; fill the cache on a miss.
  e.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') {
        const cache = await caches.open(VERSION);
        cache.put(req, res.clone());
      }
      return res;
    } catch (err) {
      throw err;
    }
  })());
});
`;

writeFileSync(`${ROOT}sw.js`, sw);
console.log(`sw.js written — ${VERSION}, ${urls.length} precache entries`);
