#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the questy-flove DATA block from the canonical catalog.

Reads fields-colours.json and emits the JS data block for
questy-flove/index.html (CATEGORIES + INPUT_FIELDS + CAT_COLOURS),
sourced from the catalog. FIELD_HINTS and CAT_QUESTIONS stay
in the page (authored text).

The curated app list (which apps appear) is preserved; the
grouping now follows the catalog's category assignments (Q6).

Usage:
  python3 build-questy-flove-data.py                  # print block
  python3 build-questy-flove-data.py --apply           # patch page
  python3 build-questy-flove-data.py --apply --dry-run # show what would change
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VOCAB = os.path.dirname(HERE)
DATA = os.path.join(VOCAB, "fields-colours.json")
QF = os.path.normpath(
    os.path.join(VOCAB, "..", "skills", "questy-flove", "index.html"))

MARK_OPEN  = "// >>> catalog data (generated by build-questy-flove-data.py — hand edits lost)"
MARK_CLOSE = "// <<< catalog data"

# Display name → catalog id (canonical Q5 mapping)
ALIAS = {
    "Goddy": "goddy", "Astry": "astry", "Hacky": "hacky", "DieSafe": "diesafe",
    "Souls": "souls", "Profily": "profily", "Sensy": "sensy", "Pracsys": "pracsys",
    "Willy": "willy", "MoralY": "cathy", "Fity": "fity", "Questy": "questy",
    "Daty": "daty", "MyFamily": "myfamily", "Maty": "maty", "Varyy": "varyy",
    "Evily": "evily", "Trusty": "trusty", "Crumbly": "crumbly", "Parenty": "parenty",
    "Lovy": "lovy", "Keys": "keys", "Fivy": "fivy", "Puzzy": "puzzy",
    "Loly": "loly", "Wisy": "wisy", "Realy": "realy", "Nety": "nety",
    "Socy": "socy", "Blogy": "blogy", "Wizy": "wizy", "Browsy": "browsy",
    "Crafty": "crafty", "Worthing": "worthing", "Lowy": "lowy", "Dealy": "dealy",
    "Freed": "freed", "Inventary": "inventary", "Minioffer": "minioffer",
    "Offer": "offer", "Rewardy": "rewardy", "Shareful": "shareful", "Wanty": "wanty",
}
ID_TO_DISPLAY = {v: k for k, v in ALIAS.items()}

# Marc (2026-09-12): the 7 formerly-picker-less apps join the qf picker, pinned
# to Economy (shareful's catalog home is Social, but it launches with the
# Economy family — the picker pins it there as decided).
PICKER_GROUP_OVERRIDE = {
    "Freed": "economy", "Inventary": "economy", "Minioffer": "economy",
    "Offer": "economy", "Rewardy": "economy", "Shareful": "economy",
    "Wanty": "economy",
}

# Stable curated display-name order (within each catalog category)
CURATED_ORDER = [
    "Goddy","Astry","Hacky","DieSafe","Souls","Profily","Sensy","Pracsys",
    "Willy","MoralY","Fity","Questy",
    "Daty","MyFamily","Maty","Varyy","Evily","Trusty","Crumbly","Parenty","Lovy",
    "Keys","Fivy","Puzzy","Loly","Wisy",
    "Realy","Nety","Socy","Blogy","Wizy","Browsy",
    "Crafty","Worthing","Lowy","Dealy","Freed","Inventary","Minioffer",
    "Offer","Rewardy","Shareful","Wanty",
]


def generate(cat_data):
    apps = {a["id"]: a for a in cat_data["apps"]}
    cats = {c["name"]: c for c in cat_data["categories"]}

    # Build lookup: catalog category id (lower-cased first word) → canonical name
    cat_lower = {n.split("/")[0].strip().lower(): n for n in cats}
    # Provide canonical id used in qf pages (matching qf category ids)
    qf_ids = {"inside", "mating", "ling", "social", "economy"}
    cat_to_qf = {}
    for cid in qf_ids:
        for canonical in cat_lower.values():
            if canonical.lower().startswith(cid) or cid in canonical.lower():
                cat_to_qf[canonical] = cid
                break
    # Fallbacks
    cat_to_qf.setdefault("Mating", "mating")
    cat_to_qf.setdefault("Inside", "inside")
    cat_to_qf.setdefault("Ling / Words", "ling")
    cat_to_qf.setdefault("Social", "social")
    cat_to_qf.setdefault("Economy", "economy")

    # Group curated apps by their catalog category
    groups = {}  # qf_id → {label, colour, apps:[display]}
    for name, cdata in cats.items():
        qf_id = cat_to_qf[name]
        groups[qf_id] = {
            "label": name,  # canonical catalog name (e.g. "Ling / Words")
            "colour": cdata["colour"],
            "apps": [],
        }

    for display in CURATED_ORDER:
        cid = ALIAS.get(display, display.lower())
        app = apps.get(cid)
        if not app:
            continue
        home = app.get("category", "")
        qf_id = PICKER_GROUP_OVERRIDE.get(display, "")
        if not qf_id:
            qf_id = cat_to_qf.get(home, home.lower())
        if qf_id not in groups:
            groups[qf_id] = {"label": home, "colour": "#6c5ce7", "apps": []}
        groups[qf_id]["apps"].append(display)

    # Emit
    lines = []
    lines.append("const CATEGORIES=[")
    for qf_id in ["inside", "mating", "ling", "social", "economy"]:
        g = groups[qf_id]
        apps_str = ",".join(repr(a) for a in g["apps"])
        lines.append(
            f"  {{id:'{qf_id}',label:'{g['label']}',"
            f"colour:'{g['colour']}',apps:[{apps_str}]}}," )
    lines.append("];")

    cat_colours = {qf_id: groups[qf_id]["colour"] for qf_id in groups}
    lines.append(f"const CAT_COLOURS={json.dumps(cat_colours)};")

    lines.append("")
    lines.append("// Per-app input fields (from fields-colours.json catalog, schema flove-hats/1)")
    lines.append("const INPUT_FIELDS={")
    for display in CURATED_ORDER:
        cid = ALIAS.get(display, display.lower())
        app = apps.get(cid)
        fields = sorted(app["slots"].keys()) if app else []
        lines.append(
            f"  {display}:{json.dumps(fields, ensure_ascii=False)}," )
    lines.append("};")

    # Hat metadata (flavour): hats are secondary, the parent colour weighs 50%
    # more (~60/40). HAT_COLOURS derives from the categories' own hat tags;
    # "risk" has no home category so it takes a hand-picked graphite (it can be
    # overridden by a category if one ever claims it).
    hat_colours = {}
    for cname, cdata in cats.items():
        hat = cdata.get("hat")
        if hat:
            hat_colours[hat] = cdata["colour"]
    hat_colours.setdefault("risk", "#50474e")

    app_hats = {}
    slot_hats = {}
    for display in CURATED_ORDER:
        cid = ALIAS.get(display, display.lower())
        app = apps.get(cid)
        if not app:
            continue
        if app.get("hat"):
            app_hats[display] = app["hat"]
        slot_map = {f: h for f, h in app.get("slots", {}).items() if h}
        if slot_map:
            slot_hats[display] = slot_map

    lines.append("")
    lines.append("// Hat metadata (secondary — the parent colour wins the blend ~60/40)")
    lines.append(f"const HAT_COLOURS={json.dumps(hat_colours)};")
    lines.append(f"const APP_HATS={json.dumps(app_hats)};")
    lines.append(f"const SLOT_HATS={json.dumps(slot_hats, ensure_ascii=False)};")
    return "\n".join(lines)


def apply_patch(page_text, block):
    marker_re = re.compile(
        re.escape(MARK_OPEN) + r".*?" + re.escape(MARK_CLOSE),
        re.DOTALL)
    marked = MARK_OPEN + "\n" + block + "\n" + MARK_CLOSE
    if marker_re.search(page_text):
        return marker_re.sub(marked, page_text)
    # First application: replace the old data section
    pattern = re.compile(
        r"(// ===== DATA =====\n).*?(\nconst FIELD_HINTS=)",
        re.DOTALL)
    result, n = pattern.subn(
        r"\1" + MARKED_OPEN_RAW + block + "\n" + MARK_CLOSE + r"\2",
        page_text, count=1)
    if n == 0:
        print("ERROR: could not find insertion point in", QF, file=sys.stderr)
        sys.exit(1)
    return result


MARKED_OPEN_RAW = MARK_OPEN + "\n"

def main():
    import argparse
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--apply", action="store_true",
                   help="Patch questy-flove/index.html in place")
    p.add_argument("--dry-run", action="store_true",
                   help="With --apply, print the diff summary only")
    args = p.parse_args()

    with open(DATA, encoding="utf-8") as fh:
        cat_data = json.load(fh)
    block = generate(cat_data)

    if not args.apply:
        print(block)
        return 0

    with open(QF, encoding="utf-8") as fh:
        text = fh.read()
    patched = apply_patch(text, block)
    if patched == text:
        print("nothing changed", file=sys.stderr)
        return 0
    if args.dry_run:
        old_lines = text.splitlines()
        new_lines = patched.splitlines()
        added = len(new_lines) - len(old_lines)
        print(f"diff: {len(old_lines)} → {len(new_lines)} lines ({added:+d})")
        return 0
    with open(QF, "w", encoding="utf-8") as fh:
        fh.write(patched)
    print("patched", QF, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
